artifacts_root: artifacts
data_transformation:
  classes_path: artifacts/data_transformation/6/classes.pkl
  preprocessor_path: artifacts/data_transformation/6/preprocessor.pkl
  root_dir: artifacts/data_transformation/6
  train_data_path: artifacts/data_correction/train_data.pkl
  train_features_path: artifacts/data_transformation/6/train_features.pkl
  train_target_path: artifacts/data_transformation/6/train_target.pkl
  val_data_path: artifacts/data_correction/val_data.pkl
  val_features_path: artifacts/data_transformation/6/val_features.pkl
  val_target_path: artifacts/data_transformation/6/val_target.pkl
model_evaluation:
  model_path: artifacts/model_trainer/XGB_1/best_model.pkl
  preprocessor_path: artifacts/data_transformation/10/preprocessor.pkl
  result: artifacts/model_evaluation/result.txt
  root_dir: artifacts/model_evaluation/
  test_data_path: artifacts/data_correction/test_data.pkl
model_trainer:
  best_model_path: artifacts/model_trainer/XGB_4/best_model.pkl
  list_monitor_components_path: artifacts/monitor_desc/list_monitor_components.pkl
  monitor_desc_folder_path: artifacts/monitor_desc
  root_dir: artifacts/model_trainer/XGB_4
  train_feature_path: artifacts/data_transformation/6/train_features.pkl
  train_target_path: artifacts/data_transformation/6/train_target.pkl
  val_feature_path: artifacts/data_transformation/6/val_features.pkl
  val_target_path: artifacts/data_transformation/6/val_target.pkl
